from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, EmailStr


# Base Schema used for creating and returning an User
class UserBase(BaseModel):
    username: str = Field(min_length=1, max_length=50)
    email: EmailStr = Field(max_length=120)


# Schema for creating an User
class UserCreate(UserBase):
    pass


# Schema for returning an User
class UserResponse(UserBase):
    # Allows pydantic to read data from attributes, not just dictionanries
    model_config = ConfigDict(from_attributes=True)

    id: int
    image_file: str | None
    image_path: str


# Base Schema used for creating and returning a Post
class PostBase(BaseModel):
    # Specifying type, and constraints
    title: str = Field(min_length=1, max_length=100)
    content: str = Field(min_length=1)


# Schema for creating a Post
class PostCreate(PostBase):
    # Temporary
    user_id: int


# Schema for returning a Post
class PostResponse(PostBase):
    # Allows pydantic to read data from attributes, not just dictionanries
    model_config = ConfigDict(from_attributes=True)

    # Adding more fields generated by the system
    id: int
    user_id: int
    date_posted: datetime
    author: UserResponse