from pydantic import BaseModel, ConfigDict, Field


# Base Schema used for creating and returning a Post
class PostBase(BaseModel):
    # Specifying type, and constraints
    title: str = Field(min_length=1, max_length=100)
    content: str = Field(min_length=1)
    author: str = Field(min_length=1, max_length=50)


# Schema for creating a Post
class PostCreate(PostBase):
    pass


# Schema for returning a Post
class PostResponse(PostBase):
    # Allows pydantic to read data from attributes, not just dictionanries
    model_config = ConfigDict(from_attributes=True)

    # Adding more fields generated by the system
    id: int
    date_posted: str